
networks:
  bridge:

services:
  nats:
    image: nats:2.10.10-alpine3.19
    command:
      - "-js"
      - "-sd"
      - "/var/local/nats"
    ports:
      - "4222:4222"
      - "8222:8222"
      - "6222:6222"
    volumes:
      - ".data/nats:/var/local/nats"
    networks:
        - bridge

  postgres:
    image: postgres:16-alpine3.19
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    ports:
      - "5432:5432"
    volumes:
      - ".data/postgresql/data:/var/lib/postgresql/data"
    networks:
        - bridge

  backend:
    build:
      target: backend
    networks:
        - bridge
    ports:
      - "8080:8080"
    develop:
      watch:
        - action: rebuild
          path: ./backend
          target: /app/backend
        - action: rebuild
          path: ./pkg
          target: /app/pkg
  worker:
    build:
      target: worker
    command:
      - "-template"
      - ${CONFIG}
    networks:
        - bridge
    develop:
      watch:
        - action: rebuild
          path: ./worker
          target: /app/worker
        - action: rebuild
          path: ./pkg
          target: /app/pkg
