
networks:
  bridge:

services:
  nats:
    image: nats:2.10.10-alpine3.19
    command:
      - "-js"
      - "-sd"
      - "/var/local/nats"
    ports:
      - "4222:4222"
      - "8222:8222"
      - "6222:6222"
    volumes:
      - ".data/nats:/var/local/nats"
    networks:
        - bridge

  worker:
    build:
      target: worker
    command:
      - "-template"
      - ${CONFIG}
    networks:
        - bridge
    develop:
      watch:
        - action: rebuild
          path: ./worker
          target: /app/worker
        - action: rebuild
          path: ./pkg
          target: /app/pkg

